### PR TITLE
[Deezer]

### PR DESCRIPTION
**Pull request by blackjack4494**
https://github.com/ytdl-org/youtube-dl/pull/22074
@LucBerge
@Jan-NiklasB

I will merge this one first and will have a look at this
https://github.com/LucBerge/youtube-dl/tree/deezer_uncipher

There are some major modifications. I don't know about license issues and/or legal issues. Maybe this branch will then be separate. There could be hint in the normal youtube-dlc version that there is a version with full deezer support.  
Also is it your code?

### CODE REVIEW

**Comment by blackjack4494** [comment]
There are some things still not working like
`https://www.deezer.com/de/track/NUMBER`

**Comment by 07416** [comment]
I assume that there won't be any legal issues since the "free" accounts have unlimited streaming access on desktop, limitless "skips", "scrubbing" and all.

>For now, this extractor only supports the 30 second previews. Patches welcome!

I'd highly appreciated full support!

**Comment by blackjack4494** [comment]
> There won't be any legal issues compared to youtube-dl since the "free" accounts have unlimited streaming access on desktop, limitless "skips", "scrubbing" and all.
> 
> > For now, this extractor only supports the 30 second previews. Patches welcome!
> 
> I'd highly appreciated full support!

I've seen some projects already offline because of dmca takedowns. The problem here is that Deezer is encrypting their songs and decrypting the in the browser when you play them. It's illegal in most countries to decrypt them or even own or offer a tool that is capable of. Only exception in most of the cases is an article describing how it would work (to decrypt) but without any actual implementations offered to download. 
So until the situation isn't fully cleared I won't risk any complaints regarding this. Tho it may be possible to compile it on your own for now.

**Comment by LucBerge** [comment]
> 
> 
> There are some things still not working like
> `https://www.deezer.com/de/track/NUMBER`
> 
> Someone with premium account could test this site as well.

I've done the [single track extractor](https://github.com/LucBerge/youtube-dl/commit/b48dba56a0d1827b89a93a22ed59b2715cb081ec#diff-361bf19193f0c9bd15ae8db082698f33). If a specific url is not working, I'll need the full stack trace using the -v option to fix it.

**Comment by 07416** [comment]
> 
> I've seen some projects already offline because of dmca takedowns. The problem here is that Deezer is encrypting their songs and decrypting them in the browser when you play them. It's illegal in most countries to decrypt them or even own or offer a tool that is capable of doing that without having any rights to do so. Only exception in most of the cases is an article describing how it would work (to decrypt) but without any actual implementations offered to download.
> So until the situation isn't fully cleared I won't risk any complaints regarding this. Tho it may be possible to compile it on your own for now.

Are the Deezer songs decrypted in the web player which runs with EME disabled in Firefox?

**Comment by blackjack4494** [comment]
> Are the Deezer songs decrypted in the web player which runs with EME disabled in Firefox?
I don't think so it's not using CDM as far as I know but rather their raw tracks that are modified. You can download them when you check network tab. However when you download them (or open the track in a new tab in browser) and play them you notice they are very different to what you can hear when you listen to it in the browser [on deezer].  
That is because they alter the track in some way.  
According to the [decryption branch](https://github.com/LucBerge/youtube-dl/tree/deezer_uncipher) it [deezer] is using blowfish cipher for their tracks.  
There are also other projects [[1]](https://github.com/kmille/deezer-downloader) showcasing how to decrypt tracks with blowfish and the given key.

Here are some DMCAs
https://github.com/github/dmca/blob/master/2018/2018-01-12-Deezer.md
https://github.com/github/dmca/blob/master/2018/10/2018-10-29-Deezer.md
https://github.com/github/dmca/blob/master/2018/2018-03-13-Deezer.md
You can find more in that repository.  

I am absolutely NOT WILLING to risk the project for ONE extractor. It wouldn't be fair for other users if this project would be taken down because of a DMCA complaint. So for now options would be to use another fork or dedicated project. An alternative could be that someone makes a script that does the decryption so you can download tracks with youtube-dlc and use thex `exec` parameter to use that script to be able to decrypt it.

**Pull request merged**
