### PR TITLE
[hotstar] Move to API v1

### PR DESCRIPTION
**Pull request by theincognito-inc**
---

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix

---

### Description of your *pull request* and other information

Fixes Hotstar extractor. Tested by me and other community members. Original PR: https://github.com/ytdl-org/youtube-dl/pull/25443 . Just did a PR to make things easier for you. As you can see, the original commit is preserved.

### CODE REVIEW

**Comment by blackjack4494** [comment]
related:
https://github.com/ytdl-org/youtube-dl/pull/25443

https://github.com/blackjack4494/youtube-dlc/issues/47
https://github.com/ytdl-org/youtube-dl/issues/25003
https://github.com/ytdl-org/youtube-dl/issues/24707
https://github.com/ytdl-org/youtube-dl/issues/25042

As others seem to have tested it I will merge it.

@theincognito-inc could you post some log output with `-v` unpatched and patch to show the difference meaning that the patch works? 
A new release will come out within next few hours.

**Comment by theincognito-inc** [comment]
Sure

**Comment by theincognito-inc** [comment]
@blackjack4494 Sure.

Unpatched:

`youtube-dlc -v -F https://www.hotstar.com/in/movies/bangalore-days/1000081352
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.hotstar.com/in/movies/bangalore-days/1000081352']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.03.1
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Proxy map: {}
[hotstar] 1000081352: Downloading webpage
[hotstar] 1000081352: Downloading JSON metadata
[hotstar] 1000081352: Downloading m3u8 information
[info] Available formats for 1000081352:
format code  extension  resolution note
hls-164      mp4        854x480     164k , avc1.4D401F, mp4a.40.2
hls-201      mp4        426x240     201k , avc1.42C015, mp4a.40.2
hls-212      mp4        1280x720    212k , avc1.640028, mp4a.40.2
hls-223      mp4        640x360     223k , avc1.4D401E, mp4a.40.2
hls-269      mp4        1920x1080   269k , avc1.640028, mp4a.40.2
hls-284      mp4        1920x1080   284k , avc1.640028, mp4a.40.2 (best)`

Notice the bitrates. This is because instead of the movie, it will download a stock sample video saying you need to update Hotstar.

Patched:

`python -m youtube_dlc -v -F https://www.hotstar.com/in/movies/bangalore-days/1000081352
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.hotstar.com/in/movies/bangalore-days/1000081352']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.03.1
[debug] Git HEAD: bc842c27a
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Proxy map: {}
[hotstar] 1000081352: Downloading webpage
[hotstar] 1000081352: Downloading token
[hotstar] 1000081352: Downloading JSON metadata
[hotstar] 1000081352: Downloading m3u8 information
[info] Available formats for 1000081352:
format code  extension  resolution note
hls-164      mp4        320x180     164k , avc1.42C00C, mp4a.40.5
hls-254      mp4        426x240     254k , avc1.42C015, mp4a.40.5
hls-347      mp4        640x360     347k , avc1.4D401E, mp4a.40.5
hls-433      mp4        854x480     433k , avc1.4D401F, mp4a.40.5
hls-765      mp4        1280x720    765k , avc1.640028, mp4a.40.5
hls-1718     mp4        1920x1080  1718k , avc1.640028, mp4a.40.5 (best)`

As you can, it's showing expected bitrates, and will download the actual movie.

**Comment by vinaykapadia** [comment]
using the latest version, i'm still getting the stock video and the lower bitrates.

D:\ytdl> .\youtube-dlc.exe -v -F https://www.hotstar.com/in/movies/bangalore-days/1000081352
[debug] System config: []
[debug] User config: ['--ffmpeg-location', 'd:\\ffmpeg\\bin', '--ignore-errors']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.hotstar.com/in/movies/bangalore-days/1000081352']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.09.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[hotstar] 1000081352: Downloading webpage
[hotstar] 1000081352: Downloading JSON metadata
[hotstar] 1000081352: Downloading m3u8 information
[info] Available formats for 1000081352:
format code  extension  resolution note
hls-164      mp4        854x480     164k , avc1.4D401F, mp4a.40.2
hls-201      mp4        426x240     201k , avc1.42C015, mp4a.40.2
hls-212      mp4        1280x720    212k , avc1.640028, mp4a.40.2
hls-223      mp4        640x360     223k , avc1.4D401E, mp4a.40.2
hls-269      mp4        1920x1080   269k , avc1.640028, mp4a.40.2
hls-284      mp4        1920x1080   284k , avc1.640028, mp4a.40.2 (best)

**Comment by theincognito-inc** [comment]
@vinaykapadia It's merged now by @blackjack4494 . It should work fine now. Just tested:

> python -m youtube_dlc -v -F https://www.hotstar.com/in/movies/bangalore-days/1000081352
> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['-v', '-F', 'https://www.hotstar.com/in/movies/bangalore-days/1000081352']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] youtube-dlc version 2020.09.16
> [debug] Git HEAD: fe84e2a39
> [debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
> [debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
> [debug] Proxy map: {}
> [hotstar] 1000081352: Downloading webpage
> [hotstar] 1000081352: Downloading token
> [hotstar] 1000081352: Downloading JSON metadata
> [hotstar] 1000081352: Downloading m3u8 information
> [info] Available formats for 1000081352:
> format code  extension  resolution note
> hls-164      mp4        320x180     164k , avc1.42C00C, mp4a.40.5
> hls-254      mp4        426x240     254k , avc1.42C015, mp4a.40.5
> hls-347      mp4        640x360     347k , avc1.4D401E, mp4a.40.5
> hls-433      mp4        854x480     433k , avc1.4D401F, mp4a.40.5
> hls-765      mp4        1280x720    765k , avc1.640028, mp4a.40.5
> hls-1718     mp4        1920x1080  1718k , avc1.640028, mp4a.40.5 (best)

**Comment by vinaykapadia** [comment]
Thanks, will try that.

**Comment by vinaykapadia** [comment]
Does it take some time to show the update? `youtube-dlc.exe -U` is saying 2020.09.14 is up to date.

**Comment by theincognito-inc** [comment]
@vinaykapadia I don't know. I don't use the exe. Maybe the updater is broken? If you are using the exe, just grab the latest exe from the releases tab. https://github.com/blackjack4494/youtube-dlc/releases/download/2020.09.16/youtube-dlc.exe

**Comment by vinaykapadia** [comment]
Thanks. Still having issues.

With VPN to India:
```
.\youtube-dlc.exe -v -F https://www.hotstar.com/in/movies/bangalore-days/1000081352
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.hotstar.com/in/movies/bangalore-days/1000081352']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.16
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[hotstar] 1000081352: Downloading webpage
[hotstar] 1000081352: Downloading token
[hotstar] 1000081352: Downloading JSON metadata
[hotstar] 1000081352: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 798, in extract_info
  File "youtube_dlc\extractor\common.py", line 530, in extract
  File "youtube_dlc\extractor\hotstar.py", line 169, in _real_extract
  File "youtube_dlc\extractor\common.py", line 1350, in _sort_formats
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```
Without VPN (United States):
```
.\youtube-dlc.exe -v -F https://www.hotstar.com/in/movies/bangalore-days/1000081352
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.hotstar.com/in/movies/bangalore-days/1000081352']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.16
[debug] Python version 3.8.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[hotstar] 1000081352: Downloading webpage
[hotstar] 1000081352: Downloading token
[hotstar] 1000081352: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "youtube_dlc\extractor\common.py", line 627, in _request_webpage
  File "youtube_dlc\YoutubeDL.py", line 2278, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by blackjack4494** [comment]
@vinaykapadia 

I used the vpn details you sent me. Connected to India (Country) Server was `#77`.  
I then tried to play the video in the browser. That didn't work.  
But this did  

> PS D:\gitkraken\youtube-dl> youtube-dlc "https://www.hotstar.com/in/movies/bangalore-days/1000081352" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.hotstar.com/in/movies/bangalore-days/1000081352', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.16
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[hotstar] 1000081352: Downloading webpage
[hotstar] 1000081352: Downloading token
[hotstar] 1000081352: Downloading JSON metadata
[hotstar] 1000081352: Downloading m3u8 information
[info] Available formats for 1000081352:
format code  extension  resolution note
hls-164      mp4        320x180     164k , avc1.42C00C, mp4a.40.5
hls-254      mp4        426x240     254k , avc1.42C015, mp4a.40.5
hls-347      mp4        640x360     347k , avc1.4D401E, mp4a.40.5
hls-433      mp4        854x480     433k , avc1.4D401F, mp4a.40.5
hls-765      mp4        1280x720    765k , avc1.640028, mp4a.40.5
hls-1718     mp4        1920x1080  1718k , avc1.640028, mp4a.40.5 (best)

So I assume you just picked a faulty vpn which was blocked or so.   
Downloading also works  

> PS D:\gitkraken\youtube-dl> youtube-dlc "https://www.hotstar.com/in/movies/bangalore-days/1000081352"      
[hotstar] 1000081352: Downloading webpage
[hotstar] 1000081352: Downloading token
[hotstar] 1000081352: Downloading JSON metadata
[hotstar] 1000081352: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2464
[download] Destination: Bangalore Days-1000081352.mp4
[download]   0.3% of ~1.38GiB at 440.89KiB/s ETA 02:57:51

**Comment by vinaykapadia** [comment]
@blackjack4494 i'm also using Nord. I'll try with server #77.

**Comment by vinaykapadia** [comment]
It worked, thanks!

**Comment by sumit-1988** [comment]
Is it working ?

**Comment by vinaykapadia** [comment]
@sumit-1988 Yes.

**Comment by blackjack4494** [comment]
@sumit-1988 and @vinaykapadia did you try the latest version?

**Pull request merged**
