### PR TITLE
[rai] Fix extraction for recent raiplay.it updates

### PR DESCRIPTION
**Pull request by blackjack4494**
https://github.com/ytdl-org/youtube-dl/pull/23040

### CODE REVIEW

**Comment by blackjack4494** [comment]
@iamleot
@fabio1962
@mauro-r

**Comment by blackjack4494** [comment]
old
```
PS D:\gitkraken\youtube-dl> youtube-dl "https://www.raiplay.it/video/2014/04/Report-del-07042014-cb27157f-9dd0-4aee-b788-b1f67643a391.html" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.raiplay.it/video/2014/04/Report-del-07042014-cb27157f-9dd0-4aee-b788-b1f67643a391.html', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading video JSON
ERROR: cb27157f-9dd0-4aee-b788-b1f67643a391: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\rai.py", line 174, in _real_extract
    '%s?json' % url, video_id, 'Downloading video JSON')
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 892, in _download_json
    expected_status=expected_status)
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 876, in _download_json_handle
    fatal=fatal), urlh
  File "c:\users\tom-oliver heidel\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 903, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: cb27157f-9dd0-4aee-b788-b1f67643a391: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

patched
```
PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://www.raiplay.it/video/2014/04/Report-del-07042014-cb27157f-9dd0-4aee-b788-b1f67643a391.html" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.raiplay.it/video/2014/04/Report-del-07042014-cb27157f-9dd0-4aee-b788-b1f67643a391.html', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.06
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading video JSON
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading XML metadata for platform mon
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading m3u8 information
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading XML metadata for platform flash
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading XML metadata for platform native
format code  extension  resolution note
hls-844      mp4        700x394     844k , avc1.77.30, mp4a.40.2
hls-1843     mp4        1024x576   1843k , avc1.77.30, mp4a.40.2 (best)
```

**Comment by mauro-r** [comment]
Hi, thanks for the update, does it mean this patch is going to be 
implemented on next youtube-dl.exe update ?
Best regards

**Comment by fabio1962** [comment]
thanks

**Comment by blackjack4494** [comment]
@mauro-r I don't think youtube-dl will. But it's added to youtube-dlc feel free to use it. There is also a windows exe available. Check readme or releases directly.

**Comment by mauro-r** [comment]
that is true, I believed you were fixing youtube-dl, sorry about.
Ok, I've downloaded youtube-dlc and it works perfectly!
Thank you much


Il 14/09/2020 07:25, Tom-Oliver Heidel ha scritto:

**Comment by blackjack4494** [comment]
No problem. I was trying to help people using youtube-dl by answering issues and pointing to possible solutions and would have helped them to maintain pull requests etc. But they banned as apparently I am not welcomed anymore to help other users.
If you experience any other problems let me know or open an issue.
Glad to hear it worked :)

**Comment by mauro-r** [comment]
Hi Tom, my RAIPLAY downloads attempt returned to be in an error state 
with youtube-dlc , same message as when it was not working with youtube-dl.
I've also kept youtube-dlc application updated.
Thank you

Il 14/09/2020 09:14, Tom-Oliver Heidel ha scritto:

**Comment by blackjack4494** [comment]
@mauro-r 
Send your output with `-v` so I can see the tested link and the error it's throwing.

**Comment by mauro-r** [comment]
Hi, here's the output:

C:\Users\mauro\Videos\download>youtube-dlc 
https://www.raiplay.it/video/2020/09/Le-Ragazze---02-10-2020-5d823024-c2fb-418f-b55b-e45dbce07b71.html 
-v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: 
['https://www.raiplay.it/video/2020/09/Le-Ragazze---02-10-2020-5d823024-c2fb-418f-b55b-e45dbce07b71.html', 
'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[RaiPlay] 5d823024-c2fb-418f-b55b-e45dbce07b71: Downloading video JSON
ERROR: 5d823024-c2fb-418f-b55b-e45dbce07b71: Failed to parse JSON 
(caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); 
please report this issue on https://yt-dl.org/bug . Make sure you are 
using the latest version; type  youtube-dl -U  to update. Be sure to 
call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", 
line 904, in _parse_json
   File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
   File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
   File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", 
line 904, in _parse_json
   File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
   File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
   File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", 
line 797, in extract_info
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", 
line 532, in extract
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\rai.py", 
line 174, in _real_extract
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", 
line 897, in _download_json
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", 
line 881, in _download_json_handle
   File "C:\Users\dst\AppData\Roaming\Build 
archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", 
line 908, in _parse_json
youtube_dl.utils.ExtractorError: 5d823024-c2fb-418f-b55b-e45dbce07b71: 
Failed to parse JSON (caused by ValueError('Expecting value: line 1 
column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug 
. Make sure you are using the latest version; type  youtube-dl -U  to 
update. Be sure to call youtube-dl with the --verbose flag and include 
its complete output.

Il 04/10/2020 21:59, Tom-Oliver Heidel ha scritto:

**Comment by blackjack4494** [comment]
@mauro-r 
>youtube-dlc "https://www.raiplay.it/video/2020/09/Le-Ragazze---02-10-2020-5d823024-c2fb-418f-b55b-e45dbce07b71.html" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.raiplay.it/video/2020/09/Le-Ragazze---02-10-2020-5d823024-c2fb-418f-b55b-e45dbce07b71.html', '-v']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.09.23-2
[debug] Python version 3.7.8 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.17, ffprobe 2.8.17
[debug] Proxy map: {}
[RaiPlay] 5d823024-c2fb-418f-b55b-e45dbce07b71: Downloading video JSON
[RaiPlay] 5d823024-c2fb-418f-b55b-e45dbce07b71: Downloading XML metadata for platform mon
[RaiPlay] 5d823024-c2fb-418f-b55b-e45dbce07b71: Downloading m3u8 information
[RaiPlay] 5d823024-c2fb-418f-b55b-e45dbce07b71: Downloading XML metadata for platform flash
[RaiPlay] 5d823024-c2fb-418f-b55b-e45dbce07b71: Downloading XML metadata for platform native
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://uscreativemedia6-vh.akamaihd.net/i/podcastcdn/raitre/Le_ragazze/13204698_,800,1800,2400,.mp4.csmil/index_2_av.m3u8?null=0'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 709
[download] Destination: Le Ragazze-5d823024-c2fb-418f-b55b-e45dbce07b71.mp4
[download]   1.0% of ~2.19GiB at  1.42MiB/s ETA 07:06

Try downloading [latest version](https://github.com/blackjack4494/youtube-dlc/releases/tag/2020.09.30)

**Comment by mauro-r** [comment]
yes, that works!
I believed already had the latest version: if attempt updating now from 
inside my last app version (youtube-dlc -U),  it is adviced to be the 
latest (2020 09 20) .
Thank you

Il 05/10/2020 19:41, Tom-Oliver Heidel ha scritto:

**Comment by blackjack4494** [comment]
> yes, that works! I believed already had the latest version: if attempt updating now from inside my last app version (youtube-dlc -U),  it is adviced to be the latest (2020 09 20) . Thank you

The internal updater isn't working as of now. But I have a new version ready. Just have to test it before I roll it out.

**Comment by blackjack4494** [comment]
@timendum
https://github.com/ytdl-org/youtube-dl/pull/26096
Is that PR still needed?
@iamleot since you also commented on the PR

**Comment by iamleot** [comment]
@blackjack4494 No, I don't think so. AFAICT ytdl-org#26096 addresses only a subset of problems addressed by ytdl-org#23040.

**Pull request merged**
